### ISSUE TITLE
Not able to sift.py running

### ISSUE THREAD

**Issue by frajos100** [AVatch/jigsolved#1]
Was looking for a solution that can detect exactly where a jigsaw puzzle piece would fit in the full image.
Have gone through the sift.py https://gist.github.com/AVatch/843a9e5ed9cd1214676c849c7ff6736d#file-sift-py  but faced with issues running the code.
Loved the article that you had published https://medium.com/cornell-tech/jigsolved-computer-vision-to-solve-jigsaw-puzzles-70b8ad8099e5  but not finding any workable solution out there..

Although even having the data folder downloaded locally https://github.com/AVatch/jigsolved  the code sift.py displayed the below error.

Traceback (most recent call last):
  File "sift.py", line 25, in <module>
    contours, contour_index = identify_contour(piece.copy())
  File "sift.py", line 17, in identify_contour
    return contours, contour_sorted[-2]
IndexError: index -2 is out of bounds for axis 0 with size 1

**Comment by AVatch** [comment]
Hey thanks for opening this - it's been a while since I did this, but I will look it over this weekend! My guess is this is something to do w/ me hardcoding indexes since I was just experimenting, so some print debuging will help :)

**Comment by ghost** [comment]
got the same issue.what's the solution?
